export const ROLE_CATALOGS = {
    "Backend Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "JavaScript (Node.js)",
            "C#",
            "PHP",
            "Ruby",
            "Rust",
            "Kotlin",
            "Scala"
        ],
        "frameworks": [
            "Express.js",
            "FastAPI",
            "Spring Boot",
            "Django",
            "Flask",
            "NestJS",
            "Laravel",
            "ASP.NET Core",
            "Gin"
        ],
        "databases": [
            "PostgreSQL",
            "MySQL",
            "SQL Server",
            "MongoDB",
            "Redis",
            "Cassandra",
            "DynamoDB",
            "SQLite",
            "Oracle"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "REST API",
            "GraphQL",
            "JWT",
            "OAuth",
            "Authentication",
            "Authorization",
            "Microservices",
            "System Design",
            "Design Patterns",
            "Caching",
            "WebSockets",
            "Message Queues"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Frontend Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "JavaScript",
            "HTML5",
            "CSS3",
            "Dart"
        ],
        "frameworks": [
            "React",
            "Next.js",
            "Angular",
            "Vue.js",
            "Svelte",
            "Redux",
            "Tailwind CSS",
            "Bootstrap",
            "Material UI"
        ],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Responsive Design",
            "Accessibility",
            "State Management",
            "SPA",
            "SSR",
            "REST API",
            "GraphQL",
            "Performance Optimization"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Full Stack Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "JavaScript",
            "C#",
            "PHP",
            "Rust"
        ],
        "frameworks": [
            "React",
            "Next.js",
            "Node.js",
            "Express.js",
            "FastAPI",
            "Spring Boot",
            "Django",
            "Laravel"
        ],
        "databases": [
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "Redis",
            "SQLite"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Software Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "C#",
            "JavaScript",
            "PHP",
            "Rust"
        ],
        "frameworks": [
            "Spring Boot",
            ".NET",
            "FastAPI",
            "Django",
            "React",
            "Angular"
        ],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "OOP",
            "Data Structures",
            "Algorithms",
            "Design Patterns",
            "Unit Testing",
            "Debugging",
            "Version Control"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Python Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "SQL",
            "JavaScript",
            "Bash"
        ],
        "frameworks": [
            "Django",
            "Flask",
            "FastAPI",
            "Celery",
            "SQLAlchemy",
            "Pydantic"
        ],
        "databases": [
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "Redis",
            "SQLite"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "AI Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "R",
            "Julia"
        ],
        "frameworks": [
            "PyTorch",
            "TensorFlow",
            "Keras",
            "Scikit-learn",
            "LangChain",
            "LlamaIndex",
            "Hugging Face",
            "OpenAI API",
            "Haystack",
            "AutoGen"
        ],
        "databases": [
            "PostgreSQL",
            "MongoDB",
            "Pinecone",
            "ChromaDB",
            "FAISS",
            "Weaviate",
            "Milvus"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "LLMs",
            "RAG",
            "Prompt Engineering",
            "NLP",
            "Computer Vision",
            "Embeddings",
            "Vector Search",
            "Fine-tuning",
            "AI Agents",
            "MLOps"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Machine Learning Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "R",
            "Julia"
        ],
        "frameworks": [
            "Scikit-learn",
            "TensorFlow",
            "PyTorch",
            "XGBoost",
            "LightGBM",
            "MLflow",
            "Kubeflow",
            "Airflow"
        ],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Feature Engineering",
            "Model Training",
            "Model Deployment",
            "Hyperparameter Tuning",
            "Model Monitoring",
            "MLOps"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Data Scientist": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "R",
            "SQL",
            "Julia"
        ],
        "frameworks": [
            "Pandas",
            "NumPy",
            "Scikit-learn",
            "TensorFlow",
            "PyTorch",
            "Matplotlib",
            "Plotly",
            "Seaborn"
        ],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Statistics",
            "Exploratory Data Analysis",
            "Machine Learning",
            "Predictive Analytics",
            "Data Visualization",
            "A/B Testing"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Data Analyst": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "SQL",
            "R"
        ],
        "frameworks": [],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "Power BI",
            "Tableau",
            "Excel",
            "Looker",
            "Pandas"
        ],
        "concepts": [
            "SQL",
            "Dashboarding",
            "KPIs",
            "Reporting",
            "Data Cleaning",
            "Visualization"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Business Analyst": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "SQL"
        ],
        "frameworks": [],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "Excel",
            "Power BI",
            "Jira",
            "Confluence",
            "Visio",
            "Lucidchart"
        ],
        "concepts": [
            "Requirement Gathering",
            "BRD",
            "FRD",
            "User Stories",
            "Process Mapping",
            "Stakeholder Management",
            "Agile"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "DevOps Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "Bash",
            "PowerShell"
        ],
        "frameworks": [
            "Terraform",
            "Ansible",
            "Helm",
            "Packer",
            "ArgoCD",
            "Pulumi"
        ],
        "databases": [
            "PostgreSQL",
            "MySQL",
            "Redis",
            "MongoDB"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "CI/CD",
            "Infrastructure as Code",
            "Containers",
            "Kubernetes",
            "Monitoring",
            "Logging",
            "GitOps",
            "High Availability"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Design solutions",
            "Develop and maintain systems",
            "Monitor production",
            "Troubleshoot issues",
            "Optimize performance",
            "Write documentation",
            "Collaborate with cross-functional teams",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Cloud Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "Bash",
            "PowerShell"
        ],
        "frameworks": [
            "Terraform",
            "CloudFormation",
            "Pulumi",
            "Serverless Framework"
        ],
        "databases": [
            "DynamoDB",
            "Cloud SQL",
            "Cosmos DB",
            "RDS"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Cloud Architecture",
            "Networking",
            "Load Balancing",
            "IAM",
            "Autoscaling",
            "Disaster Recovery"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Design solutions",
            "Develop and maintain systems",
            "Monitor production",
            "Troubleshoot issues",
            "Optimize performance",
            "Write documentation",
            "Collaborate with cross-functional teams",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Cyber Security Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "Bash",
            "PowerShell"
        ],
        "frameworks": [
            "Metasploit",
            "Burp Suite",
            "OWASP ZAP",
            "Wireshark",
            "Nmap"
        ],
        "databases": [
            "SIEM",
            "Splunk",
            "Elastic Stack"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "OWASP Top 10",
            "Penetration Testing",
            "IAM",
            "Network Security",
            "Vulnerability Assessment",
            "Threat Modeling"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Design solutions",
            "Develop and maintain systems",
            "Monitor production",
            "Troubleshoot issues",
            "Optimize performance",
            "Write documentation",
            "Collaborate with cross-functional teams",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "QA Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "JavaScript"
        ],
        "frameworks": [
            "Selenium",
            "Playwright",
            "Cypress",
            "JUnit",
            "TestNG",
            "PyTest"
        ],
        "databases": [
            "MySQL",
            "PostgreSQL",
            "SQL Server"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Manual Testing",
            "API Testing",
            "Regression Testing",
            "Smoke Testing",
            "Test Planning",
            "Bug Tracking"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Design solutions",
            "Develop and maintain systems",
            "Monitor production",
            "Troubleshoot issues",
            "Optimize performance",
            "Write documentation",
            "Collaborate with cross-functional teams",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Automation Test Engineer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "JavaScript"
        ],
        "frameworks": [
            "Playwright",
            "Cypress",
            "Selenium",
            "Robot Framework",
            "Appium"
        ],
        "databases": [
            "MySQL",
            "PostgreSQL"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Test Automation",
            "BDD",
            "Page Object Model",
            "CI/CD Testing",
            "Performance Testing",
            "Cross-browser Testing"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Design solutions",
            "Develop and maintain systems",
            "Monitor production",
            "Troubleshoot issues",
            "Optimize performance",
            "Write documentation",
            "Collaborate with cross-functional teams",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Mobile Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "Kotlin",
            "Swift",
            "Dart",
            "Objective-C",
            "JavaScript"
        ],
        "frameworks": [
            "Flutter",
            "React Native",
            "Android SDK",
            "Jetpack Compose",
            "SwiftUI",
            "UIKit",
            "Xamarin",
            "Ionic",
            "Cordova"
        ],
        "databases": [
            "SQLite",
            "Room",
            "Realm",
            "Firebase",
            "Hive",
            "Core Data"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "Mobile UI",
            "Offline Sync",
            "Push Notifications",
            "State Management",
            "App Security",
            "API Integration",
            "Performance Optimization"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "UI/UX Designer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go"
        ],
        "frameworks": [],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "Figma",
            "Adobe XD",
            "Sketch",
            "Photoshop",
            "Illustrator",
            "InVision",
            "Zeplin",
            "Miro",
            "FigJam",
            "Canva"
        ],
        "concepts": [
            "Wireframing",
            "Prototyping",
            "User Research",
            "Design Systems",
            "Accessibility",
            "Information Architecture",
            "Interaction Design",
            "Usability Testing",
            "Responsive Design"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Product Manager": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go"
        ],
        "frameworks": [],
        "databases": [],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "Jira",
            "Confluence",
            "Trello",
            "Asana",
            "Notion",
            "Miro",
            "Figma",
            "Productboard",
            "Aha!",
            "Excel"
        ],
        "concepts": [
            "Product Strategy",
            "Roadmapping",
            "Agile",
            "Scrum",
            "User Stories",
            "OKRs",
            "Market Research",
            "Stakeholder Management",
            "Prioritization",
            "Product Analytics"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    "Java Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "Java EE",
            "Groovy",
            "Kotlin"
        ],
        "frameworks": [
            "Spring Boot",
            "Spring MVC",
            "Spring Security",
            "Hibernate",
            "Maven",
            "Gradle",
            "Jakarta EE",
            "Quarkus",
            "Micronaut"
        ],
        "databases": [
            "Oracle",
            "MySQL",
            "PostgreSQL",
            "SQL Server",
            "MongoDB",
            "Redis"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "OOP",
            "Multithreading",
            "JVM",
            "Collections",
            "Microservices",
            "REST APIs",
            "Design Patterns"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    },
    ".NET Developer": {
        "languages": [
            "Python",
            "C",
            "C++",
            "Java",
            "TypeScript",
            "Go",
            "C#",
            "VB.NET",
            "F#"
        ],
        "frameworks": [
            "ASP.NET Core",
            ".NET",
            "Entity Framework",
            "Blazor",
            "MVC",
            "Web API",
            "SignalR",
            "xUnit",
            "NUnit"
        ],
        "databases": [
            "SQL Server",
            "PostgreSQL",
            "MySQL",
            "Oracle",
            "Cosmos DB",
            "Redis"
        ],
        "cloudDevops": [
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "Jenkins",
            "Linux",
            "Terraform",
            "Nginx",
            "Prometheus",
            "Grafana",
            "Google"
        ],
        "tools": [
            "VS Code",
            "IntelliJ IDEA",
            "Postman",
            "Swagger",
            "Jira",
            "Confluence",
            "GitHub Actions",
            "SonarQube",
            "Maven",
            "Gradle"
        ],
        "concepts": [
            "MVC",
            "Dependency Injection",
            "LINQ",
            "Async Programming",
            "REST APIs",
            "Microservices",
            "Authentication",
            "Azure Services"
        ],
        "preferredSkills": [],
        "responsibilities": [
            "Develop new features",
            "Build scalable applications",
            "Fix production bugs",
            "Write unit tests",
            "Review code",
            "Collaborate with cross-functional teams",
            "Optimize performance",
            "Maintain documentation",
            "Deploy applications",
            "Participate in Agile ceremonies"
        ],
        "education": [
            "B.E/B.Tech",
            "BCA",
            "MCA",
            "M.Sc Computer Science",
            "M.Tech",
            "Related Degree"
        ],
        "certifications": [
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "Microsoft",
            "Oracle",
            "Red Hat",
            "Databricks",
            "TensorFlow",
            "Scrum",
            "Flutter",
            "Android",
            "Apple",
            "ISC2 / CompTIA (Security roles)",
            "Kubernetes (CKA)",
            "Google"
        ],
        "benefits": [
            "Health Insurance",
            "Hybrid Work",
            "Remote Work",
            "Flexible Hours",
            "Paid Leave",
            "Learning Budget",
            "Performance Bonus",
            "ESOPs",
            "Relocation Assistance"
        ]
    }
};
