"""add_shortlisted

Revision ID: 47ca33fd6304
Revises: 9252f7609261
Create Date: 2026-06-17 20:37:36.494248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ca33fd6304'
down_revision: Union[str, Sequence[str], None] = '9252f7609261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('is_shortlisted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'is_shortlisted')
    # ### end Alembic commands ###
